### ISSUE TITLE
Improve the website a little bit more

### ISSUE THREAD

**Issue by ArshErgon** [ArshErgon/gitfetch#1]
As now website is using normal styling, with the help of pico.css, we can improve it little bit more, I was thinking to use daisyUI for design, and after that pushing the website to vercel.

**Comment by infm5** [comment]
@ArshErgon create a new repo  for the Website, will push the code there

**Comment by ArshErgon** [comment]
@deepraj02 um creating a new repo just for a website not worth it in my eyes, but I think making a website in another branch means separate from our main branch will be good, later we will set deployment on that branch, what you think? 
And creating a website is on me, will share some inspiration with you

**Comment by infm5** [comment]
Let me share a template with you for the website
