### ISSUE TITLE
show LoC per language

### ISSUE THREAD

**Issue by ZuseZ4** [ArshErgon/gitfetch#36]
I often wonder how much work it would be to contribute a certain feature to a repo and the LoC is a crude, but still helpful metric for that. I would like to have an easy command for that which doesn't require me to download, running cloc manually and deleting the downloaded sourecode on my own. Github unfortunately doesn't show that on the repository website itself.

**Comment by infm5** [comment]
Hey @ZuseZ4 for the suggestion, we will be implementing this option in the CLI in our Later Stable version. 😁

**Comment by ArshErgon** [comment]
Hey @ZuseZ4 thanks for the issue,
well, yeah sadly even the `graphql` and `REST` also does not the LoC query, but I have seen a query which uses LoC will be adding this feature in the top 3 or top 5 repo section which I later gonna add.
